### PR TITLE
Run migration once; wait for migrations to run before starting api 

### PR DESCRIPTION
**Pull request by sunu**
Addresses https://github.com/IFRCGo/go-api/issues/1926

Continuation of https://github.com/IFRCGo/go-api/pull/1932

### CODE REVIEW

**Comment by szabozoltan69** [comment]
Can I try a merge?

**Comment by sunu** [comment]
@szabozoltan69 this can still potentially make the api unavailable if things don't go as planned. We can try deploying together in ~ 1 hour with @batpad.

Also, looks like the the web-rewrite branch history just changed and we have a bunch of additional commits in the PR now. I'll rebase before we merge.

**Comment by szabozoltan69** [comment]
(I think we should wait the go-rewrite cutover, and let's play with this afterwards. So let's postpone the merge until Thursday.)

**Comment by tnagorra** [comment]
@szabozoltan69 @sunu Should we look into this PR as the go-rewrite is complete?

**Comment by szabozoltan69** [comment]
There were no issue regarding to this in the past year, so I close this ticket.

**Pull request closed without merging**
