### PR TITLE
add new tileset attributes

### PR DESCRIPTION
**Pull request by geohacker**
Ref https://github.com/IFRCGo/go-frontend/issues/2048

cc @jhenshall @batpad @szabozoltan69

### CODE REVIEW

**Review by szabozoltan69 — APPROVED** [review]
So these are the sources of the different filter names! Great!

**Comment by szabozoltan69** [comment]
@geohacker  is it ready to merge?

**Comment by geohacker** [comment]
@jhenshall I've gone through the spreadsheet you shared and now added all possible columns to all the tilesets. These are the attributes as of now:

## country tileset
country_id
geom
name
name_es
name_fr
name_ar
iso
region_id
iso3
independent
is_deprecated
disputed
fdrs
record_type

## district tileset
district_id
geom
name
code
country_id
is_enclave
is_deprecated
country_iso
country_iso3
country_name
country_name_es
country_name_fr
country_name_ar


## country centroid
country_id
name_en
name_ar
name_es
name_fr
independent
disputed
is_deprecated
iso
iso3
record_type
fdrs
region_id
centroid

## district centroid
district_id
country_id
name
code
is_deprecated
is_enclave
country_iso
country_iso3
country_name
country_name_es
country_name_fr
country_name_ar
centroid

@jhenshall could you confirm this is all that's needed? If yes, we can merge and update the front-end code.

**Comment by geohacker** [comment]
@szabozoltan69 no, let's wait for confirmation from @jhenshall to make sure all the attributes necessary are included here.

**Comment by jhenshall** [comment]
Looking great thanks @geohacker! The only thing: on the 'country_centroid' can we change `name_en` to `name` just so it matches across the 4 datasets. Then we're good to go.

**Comment by geohacker** [comment]
@jhenshall Done.

**Pull request merged**
