### PR TITLE
Change logic for normal user

### PR DESCRIPTION
**Pull request by k9845**
Addresses 
- https://github.com/IFRCGo/go-frontend/issues/2749

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by k9845** [comment]
@szabozoltan69 Please merge this and deploy to staging.

**Comment by szabozoltan69** [comment]
Hi @k9845 – is it ok to put this to Prod? Or still waiting to frontend release with this?

**Comment by k9845** [comment]
@szabozoltan69 Let's wait for frontend release.

**Comment by szabozoltan69** [comment]
@k9845 It's already on prod, was put on Friday.

**Pull request merged**
