### PR TITLE
Admin2 area can be deprecated

### PR DESCRIPTION
**Pull request by szabozoltan69**
Refers to https://github.com/IFRCGo/go-api/issues/1746

### CODE REVIEW

**Comment by batpad** [comment]
@szabozoltan69 this looks really good to me!

My only request would be to have some tests for this. It can be some pretty simple tests to just add one deprecated and non-deprecated Country, admin1 and admin2, and then simple tests to test all the cases and we are getting back what is expected. This is the kind of feature where any regression can be really problematic and it's just a good feeling to have tests for it.

**Comment by szabozoltan69** [comment]
@batpad Good point!
I tested it via switching is_deprecated flags in district and country (and admin2), and checked the generated SQL queries also. They are ok.
I tested these:
```
curl http://localhost:8000/api/v2/admin2/?admin1__country__iso3=TUR
curl http://localhost:8000/api/v2/admin2/?admin1__country=174
curl http://localhost:8000/api/v2/district/?country__iso3=TUR
curl http://localhost:8000/api/v2/admin2/?admin1=3075
while:
update api_admin2 set is_deprecated =false where id=3075;
update api_admin2 set is_deprecated =false where id=77;
update api_admin2 set is_deprecated =true where id=77;
update api_country set is_deprecated=false where id=174;
update api_country set is_deprecated=true where id=174;
update api_district set is_deprecated=false where id=3075;
update api_district set is_deprecated=true where id=3075;
update api_district set is_deprecated=false where id=3075;

**Comment by szabozoltan69** [comment]
Now I realized you meant some wired-in unit tests... Ok... let me see
 :-)

**Comment by tovari** [comment]
@davidmuchatiza, would you mind to do some thorough tests on Staging? I suggest to select a country where we need to change  admin1 areas and create a FR (and emergency), 3W project, 3W activity related to the emergency page and a DREF, all covering the legacy admin1 areas. 
Then lets add the new admin1s, with new IDs, indicate deprecated the legacy admins. 
Then we should check, if the old admins are still available for the created content.
cc: @szabozoltan69

**Comment by szabozoltan69** [comment]
Still not deployed yet...
The old admin2 areas are meant to be available only from backend Admin – they are not sent to frontend via API (by the plan).

**Comment by batpad** [comment]
> Now I realized you meant some wired-in unit tests... Ok... let me see

Haa, sorry - I should have been more specific - yes, I meant adding to the unit tests :-)

**Comment by szabozoltan69** [comment]
Deployed to Staging.

**Pull request merged**
