### PR TITLE
Make boolean fields nullable

### PR DESCRIPTION
**Pull request by k9845**
## Changes
- Change boolean fields to nullable

## Checklist 
Things that should succeed before merging.

- [x] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Review by szabozoltan69 — CHANGES_REQUESTED** [review]
Please change has_no_data_on_people_reached to "Has no data on people reached" in verbose_name.

**Review by szabozoltan69 — APPROVED** [review]

**Comment by k9845** [comment]
@szabozoltan69 don't merge this now, we are updating changes on same pr.

**Comment by frozenhelium** [comment]
@szabozoltan69 Please, merge this and deploy to the staging. Thanks in advance! :)

**Comment by szabozoltan69** [comment]
Deployed to staging

**Pull request merged**
