### PR TITLE
Add global endpoint for fetching enums

### PR DESCRIPTION
**Pull request by thenav56**
## Changes
Add valid enum values for each enum so that the typing is included for the frontend.
- To fetch enums http://localhost:8000/api/v2/global-enums/
- Global Enum schema http://localhost:8000/api-docs/swagger-ui/#/api/api_v2_global_enums_retrieve

## Later if needed
- [ ] Add filter to specify enums

### CODE REVIEW

**Review by k9845 — APPROVED** [review]
LGTM!

**Review by szabozoltan69 — APPROVED** [review]
I suppose that the Sectors and SectorTags are not in this list, due to they have other attributes (like color) also.
Great work anyway!

**Comment by thenav56** [comment]
Hey @szabozoltan69 
We included a few for now just to make sure everything works on the front-end side. After this is merged we will start adding others as well.

**Comment by szabozoltan69** [comment]
Maybe https://goadmin-stage.ifrc.org/api/v2/programmetype could be included also.

**Comment by szabozoltan69** [comment]
@thenav56 Deployed to Staging: https://goadmin-stage.ifrc.org/api/v2/global-enums/

**Pull request merged**
