### PR TITLE
feat: analytics logging for incoming requests

### PR DESCRIPTION
**Pull request by gulfaraz**
Addresses https://github.com/IFRCGo/go-api/issues/1026 

## Changes

* Log incoming API requests to Azure
* This PR adds a new environment variable
`APPLICATION_INSIGHTS_INSTRUMENTATION_KEY=fa128365-fb09-4568-b944-b05e38b6b94c`

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by batpad** [comment]
This looks really good to me, @gulfaraz !

@thenav56 do you mind giving this a review?

@szabozoltan69 once this is merged, we will need to add this key to the environment variables -- @gulfaraz should we setup different keys for staging and prod? or leave it undefined on staging?

Also, @gulfaraz can it be run locally without a key?

**Comment by szabozoltan69** [comment]
So I added (in both staging and prod scripts) to init-api.sh:
echo "APPLICATION_INSIGHTS_INSTRUMENTATION_KEY" >> .tmp/env
and to .env:
export APPLICATION_INSIGHTS_INSTRUMENTATION_KEY='...'
Now comes the merge and deployment... (in 10 minutes it is on staging)

**Comment by szabozoltan69** [comment]
Deployed to staging

**Comment by gulfaraz** [comment]
> can it be run locally without a key? or leave it undefined on staging?

I tried to make this possible but the Django config does not allow the variable to be optional. Maybe someone more familiar with Django can figure this out. It should be possible to use a fake key like `01234567-89ab-cdef-ghij-klmnopqrstuv`.

> should we setup different keys for staging and prod?

No need, we can filter the logs on the dashboard

**Comment by szabozoltan69** [comment]
Now there is some issue on staging... (502 bad gateway)

**Comment by szabozoltan69** [comment]
Now it is fine.

**Comment by thenav56** [comment]
@batpad All looks good to me.

@gulfaraz For defining an optional variable. You can do something like this.
```python
APPLICATION_INSIGHTS_INSTRUMENTATION_KEY = os.environ.get('APPLICATION_INSIGHTS_INSTRUMENTATION_KEY', 'this-is-a-random-key-for-local-devlo')
```
Could you also let us know what happens when the wrong key is provided (or it is run on local)? From the look of it, the invalid key is silently ignored.
Also, how does the client send the data to the server? Is there any authentication? Asking since we have shared the key publicly.

**Pull request merged**
