### PR TITLE
Add visibility in search page

### PR DESCRIPTION
**Pull request by k9845**
Addresses 
- https://github.com/IFRCGo/go-api/issues/1742#event-8922287409

## Changes
- Added visibility filter in search page result

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by k9845** [comment]
@szabozoltan69 Let's merge and deploy to staging.

**Comment by szabozoltan69** [comment]
Dera @k9845 – from now until Monday evening I am away. Please ask Navin to do the next merges and deployments to Staging.
(These two, 1744 and 1745 I do yet.)

**Comment by k9845** [comment]
@szabozoltan69 Please also run `python manage.py update_index` in staging.

**Comment by szabozoltan69** [comment]
Deployed to Staging, update_index was run fine:
```
./manage.py update_index
Indexing 5 regions
Indexing 285 countries
Indexing 3563 districts
Indexing 4434 emergencies
Indexing 3700 appeals
Indexing 10108 field reports
Indexing 351 Surge Alerts
Indexing 25 Emergency Response Units
Indexing 108 Personnels
Indexing 1722 Projects
Indexing 153 drefs
Indexing 73 Dref Operational Updates
Indexing 29 Flash updates
```

**Pull request merged**
