### PR TITLE
Project/web rewrite

### PR DESCRIPTION
**Pull request by k9845**
Addresses xxxxxx 

## Changes

* Detailed list or prose of changes
* ...

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Review by szabozoltan69 — COMMENTED** [review]
<3 Finally, tests are ok!

**Comment by k9845** [comment]
@szabozoltan69 Please don't much this branch.

**Comment by szabozoltan69** [comment]
> @szabozoltan69 Please don't much this branch.

I didn't want to much it very much.

**Comment by szabozoltan69** [comment]
> @szabozoltan69 Please don't much this branch.

I won't merge it until it's a draft, of course.

**Pull request closed without merging**
