### PR TITLE
Update develop using master

### PR DESCRIPTION
**Pull request by thenav56**
Sync develop with master

### CODE REVIEW

**Comment by szabozoltan69** [comment]
Did you really want to switch off caching in staging?

**Comment by thenav56** [comment]
@szabozoltan69 
The cache is creating issues in the staging as well.

Can you also deploy this to the K8 staging as well?

cc: @anamariaescobar @udaynwa

**Comment by szabozoltan69** [comment]
@thenav56 
To deploy to k8s just needs a merge to terraform branch. Please do it, if convenient.

**Comment by szabozoltan69** [comment]
develop->terraform

**Comment by thenav56** [comment]
Thanks @szabozoltan69

**Comment by thenav56** [comment]
@szabozoltan69 @batpad 

The pipeline finished with success but the cache is still happening in the staging. Do you guys have any idea?

https://dev.azure.com/IFRC/IFRC_GO/_build/results?buildId=19965&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=08703039-49d0-5b78-7691-5b9414c62c1d

**Comment by thenav56** [comment]
cc: @frozenhelium

**Comment by szabozoltan69** [comment]
@thenav56 @frozenhelium The deployment is not finished when the Azure pipeline shows green. It still needs 3-4 minutes.

**Comment by szabozoltan69** [comment]
You can be sure about the finished deployment via:
p=$(kubectl get pods |grep unnin|grep api|cut -d' ' -f1)
kubectl exec -it $p -- bash

and then a git log.
(Unfortunately api/v2/brief does not show the required git tag, due to the pipeline git stuff)

Otherwise I am not sure that the caching was the root cause of the issue (at least Uday's error forwarding did not show it for me).

**Comment by szabozoltan69** [comment]
@thenav56 now it contains the fresh one:
```
~/go-api# git log
commit 58203676b99bb1b22dedb3fca961efb9c69c24ba (grafted, HEAD, origin/58203676b99bb1b22dedb3fca961efb9c69c24ba)
Author: Navin Ayer <thenav56@users.noreply.github.com>
Date:   Fri Jun 9 10:50:07 2023 +0545
    Merge pull request #1807 from IFRCGo/develop
    Disable cache in staging
```

**Comment by thenav56** [comment]
Thanks @szabozoltan69, Now the cache is disabled in the staging as well.
cc: @udaynwa @frozenhelium @anamariaescobar

**Comment by szabozoltan69** [comment]
@thenav56 @frozenhelium Now I see that even https://goadmin-stage.ifrc.org/api/v2/brief is ok, it shows:
git_last_commit | "58203676" – which is fine! :-D

**Comment by szabozoltan69** [comment]
(Just the git_last_tag is not valid there.)

**Comment by szabozoltan69** [comment]
@thenav56 Please let me know if really the caching was the root cause of any nonwanted behaviour (for logged in users). I doubt it.

**Comment by udaynwa** [comment]
@szabozoltan69 , caching was the root cause for DREF while publishing. Not exactly sure how caching caused the issue, but disabling it fixed it. We are looking into further details.

**Pull request merged**
