### PR TITLE
Fix document issue for United Kingdom

### PR DESCRIPTION
**Pull request by susilnem**
Addresses
- https://github.com/IFRCGo/go-web-app/issues/669

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Review by thenav56 — APPROVED** [review]
Looks good.
Could you also include how this changes fix the United Kingdom issue?

**Comment by susilnem** [comment]
We were taking the last data while dropping duplicates which seems not working, so it has been changed to first(default) and empty country names are removed from the df.

**Comment by szabozoltan69** [comment]
Can I merge and deploy it to Staging, @susilnem ?

**Comment by susilnem** [comment]
Let's merge it @szabozoltan69

**Comment by szabozoltan69** [comment]
Merged to develop, deployed to Staging.

**Pull request merged**
