### PR TITLE
add three tabs

### PR DESCRIPTION
**Pull request by geohacker**
Addresses https://github.com/IFRCGo/go-frontend/issues/1009 

## Changes

* Adds 3 tab titles for Events
* One is by default 'Additional Information' but editable
* Snippets now take a tab number - 1, 2 or 3. This is sent in the API so the front-end can render them into different tabs.

Screenshot 2020-03-31 17 34 54

Screenshot 2020-03-31 17 34 41

/event/:id

```
name: "Test Tabs"
dtype: 66
...
id: 3570
slug: "test-the-slug-1"
tab_one_title: "Additional Information"
tab_two_title: "Maps and Charts"
tab_three_title: "Guidance"
```
/event_snippets
```
results: [,…]
0: {event: 3570, snippet: "Content for Tab 1", image: null, visibility: 3, position: 3, tab: 1, id: 134}
1: {event: 3570, snippet: "Content for Tab 2", image: null, visibility: 3, position: 3, tab: 2, id: 135}
2: {event: 3570, snippet: "Content for Tab 3", image: null, visibility: 3, position: 3, tab: 3, id: 136}
```

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

cc @necoline @batpad @GregoryHorvath

### CODE REVIEW

**Comment by necoline** [comment]
This structure makes sense to me

**Comment by geohacker** [comment]
@GregoryHorvath do you mind giving this a quick review + merge?

**Comment by geohacker** [comment]
Would be great to get it up on staging as well. Thank you @GregoryHorvath!

**Comment by batpad** [comment]
@geohacker we'd need to check up on failing tests here :(

**Comment by GregoryHorvath** [comment]
> @geohacker we'd need to check up on failing tests here :(

It seems the migrations conflict. Just run `docker-compose run --rm makemigrations_merge` and they should be fixed if everything goes right.

**Comment by geohacker** [comment]
Ok cool I can do that. Wasn't sure the best approach with migrations!

**Comment by geohacker** [comment]
@GregoryHorvath @batpad thank you, I just merged the migrations and tests pass. 👍

**Comment by geohacker** [comment]
Ping @GregoryHorvath @batpad

**Comment by GregoryHorvath** [comment]
@geohacker So sorry I was about to deploy this but got distracted and forgot about it since. Merging it and deploying it soon.

**Pull request merged**
