### PR TITLE
Solve issue for rendering html tag in email

### PR DESCRIPTION
**Pull request by Rup-Narayan-Rajbanshi**
Addresses Flash Update

## Changes
- Solve issue for rendering html tag in Email Situational Overview
- Solve issue for not rending images in email for production

## Checklist 
Things that should succeed before merging.

- [x] Updated/ran unit tests
- [x] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by szabozoltan69** [comment]
Shall I fix snapshot test mismatch?

**Comment by szabozoltan69** [comment]
@Rup-Narayan-Rajbanshi is this branch ready for merging?

**Comment by Rup-Narayan-Rajbanshi** [comment]
> @Rup-Narayan-Rajbanshi is this branch ready for merging?

No , pr review required pending.

**Review by thenav56 — APPROVED** [review]

**Comment by Rup-Narayan-Rajbanshi** [comment]
@szabozoltan69 is it deployed to stazing?

**Comment by szabozoltan69** [comment]
Deployed to staging environment

**Pull request merged**
