### PR TITLE
Feature/emergency project

### PR DESCRIPTION
**Pull request by frozenhelium**
Addresses [2233](https://github.com/IFRCGo/go-frontend/issues/2233) 

## Changes
- Model and API for Emergency 3W

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by frozenhelium** [comment]
@szabozoltan69 could you merge and deploy this to the staging?

**Comment by szabozoltan69** [comment]
Deployed to staging environment.

**Comment by szabozoltan69** [comment]
Nice work!
kép

**Comment by szabozoltan69** [comment]
"manage.py loaddata emergency_project_activity_actions.json" _done._

**Comment by frozenhelium** [comment]
Awesome! Thanks @szabozoltan69 !

**Pull request merged**
