### PR TITLE
Add internal plan to ingest_country_plan_file

### PR DESCRIPTION
**Pull request by thenav56**
Addresses
- https://github.com/IFRCGo/go-api/issues/1648 

## Changes

* Add script to load internal plan to country-plan
* Create a country plan if not exists for a given country from Appeal API
* Remove legacy cronjob from ingest_country_plan_file in favor of sentry

## To test
- Run command
  ```bash
  docker-compose exec serve ./manage.py ingest_country_plan_file
  ```
- View from admin panel `/en/country_plan/countryplan/`

### CODE REVIEW

**Review by k9845 — APPROVED** [review]

**Comment by szabozoltan69** [comment]
@thenav56 is it ready to merge? (Seems to be a Draft)

**Review by Rup-Narayan-Rajbanshi — APPROVED** [review]

**Comment by thenav56** [comment]
> @thenav56 is it ready to merge? (Seems to be a Draft, maybe we are waiting for @Rup-Narayan-Rajbanshi 's review.)

Hey @szabozoltan69, I was waiting for approval from the team. Looks like all good. If you have time please review/merge and deploy to staging.

You can use this to start the import in the server
```bash
docker-compose exec serve ./manage.py ingest_country_plan_file
```

**Comment by szabozoltan69** [comment]
Hey @thenav56 – I tried it locally and works great! Let's deploy it...

**Comment by szabozoltan69** [comment]
Deployed to staging

**Pull request merged**
