### PR TITLE
Add email alert for project near complete status

### PR DESCRIPTION
**Pull request by thenav56**
Addresses https://github.com/IFRCGo/go-api/issues/1061 

## Changes

- Send an email for the projects which status will change to `completed` in 5 days.
- Update project status on `save()`.
- Update test (+snapshot) related to projects.
- Fix flake8 issues.
- Change project-status update cronjob to once a day.

### CODE REVIEW

**Review by szabozoltan69 — APPROVED** [review]
I suppose that the crontab change was intentional.

**Comment by thenav56** [comment]
> I suppose that the crontab change was intentional.

Yes, it is intentional. I have mentioned it in the description as well.
Since we are using date instead of DateTime and we are not storing if an email sent states, we need to run the script once a day.

**Comment by szabozoltan69** [comment]
Deployed to staging

**Comment by batpad** [comment]
This looks good to me :+1:

**Pull request merged**
