### PR TITLE
Add missing strategic priority and added file validation

### PR DESCRIPTION
**Pull request by Rup-Narayan-Rajbanshi**
Addresses Country Plan

## Changes
- Add missing strategic priority

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Review by thenav56 — APPROVED** [review]

**Comment by szabozoltan69** [comment]
@frozenhelium merged, deployed to Staging.

**Comment by Rup-Narayan-Rajbanshi** [comment]
@szabozoltan69 , Thank you for deployment. Just want to know if you migrate the recent migration file for country plan.

**Comment by szabozoltan69** [comment]
> Thank you for deployment. Just want to know if you migrate the recent migration file for country plan.
Yes, the deployment of the new migration files happens at the moment of deployment.
I double checked it, and the migration was done on Staging VM:
```
Running migrations:
  Applying country_plan.0003_auto_20221128_0831... OK
```

**Comment by Rup-Narayan-Rajbanshi** [comment]
@szabozoltan69 thanks for the check. So i figured out that inorder to reflect the changes , we need to import the xlsx file once agian.

**Pull request merged**
