### PR TITLE
add Event as default value for action type

### PR DESCRIPTION
**Pull request by batpad**
Adds a default value for `field_report_type` on the Action model.

cc @thenav56 @szabozoltan69

### CODE REVIEW

**Comment by thenav56** [comment]
Hey @batpad, It's will be a good idea to use variables instead of strings. Something like this
```python
class ActionOrg:
    NATIONAL_SOCIETY = 'NTLS'
    FOREIGN_SOCIETY = 'PNS'
    FEDERATION = 'FDRN'

    CHOICES = (
        (NATIONAL_SOCIETY, 'National Society'),
        (FOREIGN_SOCIETY, 'Foreign Society'),
        (FEDERATION, 'Federation'),
    )


class ActionType:
    EVENT = 'EVT'
    EARLY_WARNING = 'EW'

    CHOICES = (
        (EVENT, 'Event'),
        (EARLY_WARNING, 'Early Warning'),
    )


class Action(models.Model):
    """ Action taken """
    name = models.CharField(max_length=100)
    organizations = ArrayField(
        models.CharField(choices=ActionOrg.CHOICES, max_length=4),
        default=list, blank=True
    )
    field_report_type = models.CharField(
        choices=ActionType.CHOICES,
        blank=True,
        default=ActionType.EVENT,
        max_length=4
    )
```

**Comment by batpad** [comment]
@thenav56 :+1: I was a bit worried to use the `Enum` class because I want to use the same choices and don't want to land up breaking the choices passed to the `ActionsTaken` model in subtle ways: https://github.com/IFRCGo/go-api/blob/master/api/models.py#L730 .

What you've outlined here makes sense. Will make this change. Thank you :+1:

**Comment by batpad** [comment]
@thenav56 pushed changes as per your suggestion. Could you give this an approval if all looks good?

@szabozoltan69 please hold off on merging until approved.

**Comment by szabozoltan69** [comment]
Hi @batpad , sorry, I've forgotten about this branch. Can I deploy master branch to staging and prod?

**Comment by batpad** [comment]
@szabozoltan69 yes. Thank you.

**Comment by szabozoltan69** [comment]
@batpad Thanks – I deployed it until "staging" only, because now there are some "notification change" (Greg's work) also in the master branch, and it should be tested carefully (before production push).

**Pull request merged**
