### PR TITLE
add alert level to events + migrations, resolves #168

### LINKED ISSUE #168: Add alert level (red, orange, green) to events
Should also ingest this from the gdacs feed where available.

### PR DESCRIPTION
**Pull request by matthewhanson**

### CODE REVIEW

**Comment by dereklieu** [comment]
@matthewhanson can we also make this an enum field? The only options should be red, orange, and green.

**Comment by matthewhanson** [comment]
@dereklieu yes, np. Will update PR later today

**Comment by matthewhanson** [comment]
@dereklieu turned into enum, synced up with develop and redid migrations.

however, it's failing tests on Circle as it's not recognizing the alert_level column.  I tried without the Circle cache and same problem so I"m not sure why it's complaining. Tests run fine locally.

I'm on my way out, but will revisit this again later.

**Comment by matthewhanson** [comment]
@dereklieu this is ready for review and merge

**Pull request merged**
