### PR TITLE
Joining country into query

### PR DESCRIPTION
**Pull request by szabozoltan69**
District table already has no iso column, but via country_id we can join it.

### CODE REVIEW

**Comment by szabozoltan69** [comment]
@geohacker Do you think this will be OK?

**Comment by szabozoltan69** [comment]
Local log: https://pastebin.com/w7ePpPzv
I suppose no updates/inserts has been executed.

**Comment by szabozoltan69** [comment]
@geohacker Could you please check this change?

**Comment by geohacker** [comment]
@szabozoltan69 the query change looks ok to me but the logs doesn't seem correct. It looks the JSON is malformed. I will need some time to set this up locally to test. 

cc @batpad

**Review by geohacker — APPROVED** [review]

**Comment by geohacker** [comment]
@szabozoltan69 @batpad this change looks good. I tested generating geojsons locally. 
Though I ran into a Mapbox Tileset error which I've no clue about:

```
root@093b08ed69eb:~/go-api#
Traceback (most recent call last):
  File "/usr/local/bin/tilesets", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mapbox_tilesets/scripts/cli.py", line 528, in upload_source
    ctx, username, id, features, no_validation, quiet, replace, token, indent
  File "/usr/local/lib/python3.6/site-packages/mapbox_tilesets/scripts/cli.py", line 615, in _upload_source
    raise errors.TilesetsError(resp.text)
mapbox_tilesets.errors.TilesetsError: {"message":"Internal Server Error"}
```

This sounds like some upstream error that we will have to wait.

**Comment by szabozoltan69** [comment]
Ok. I do not deploy "develop" branch to staging until we do not fix this ^.

**Pull request merged**
