### PR TITLE
Translations in HTML

### PR DESCRIPTION
**Pull request by szabozoltan69**
Refers to https://github.com/IFRCGo/go-api/issues/1985

### CODE REVIEW

**Comment by batpad** [comment]
Will we need to do something to re-generate translations for the existing items? cc @thenav56

**Review by batpad — APPROVED** [review]

**Comment by szabozoltan69** [comment]
> Will we need to do something to re-generate translations for the existing items? cc @thenav56

For some obvious cases I fixed database records, like this (instead of rollback of course I wrote commit, just to be safe I wrote rollback to my draft):
```
begin;
update api_countrysnippet set snippet_fr = replace(snippet_fr, ' »', '"') where id in (
select id from api_countrysnippet where snippet_fr like '% »%'
);
rollback;

begin;
update api_regionsnippet set snippet_fr = replace(snippet_fr, ' »', '"') where id in (
select id from api_regionsnippet where snippet_fr like '% »%'
);
rollback;

begin;
update api_snippet set snippet_fr = replace(snippet_fr, ' »', '"') where id in (
select id from api_snippet where snippet_fr like '% »%'
);
rollback;

begin;
update api_countrysnippet set snippet_fr = replace(snippet_fr, 'couleur :', 'color:') where id in (
select id from api_countrysnippet where snippet_fr like '%couleur :%'
);
rollback;



select id, length(description_fr) from api_fieldreport where description_fr like '% »%' order by 1 desc;
--91
select id, length(summary_fr) from api_event where summary_fr like '% »%' order by 2 desc;
--84
select id, event_id, length(snippet) from api_snippet where snippet_fr like '% »%' order by 2 desc;
select id, region_id, length(snippet) from api_regionsnippet where snippet_fr like '% »%' order by 2 desc;
select id, country_id, length(snippet) from api_countrysnippet where snippet_fr like '% »%' order by 2 desc;
select id, length(snippet) from api_regionemergencysnippet where snippet_fr like '% »%' order by 2 desc;
select id, length(snippet) from api_regionpreparednesssnippet where snippet_fr like '% »%' order by 2 desc;
select id, length(snippet) from api_regionprofilesnippet where snippet_fr like '% »%' order by 2 desc;

begin;
update api_fieldreport set description_fr = replace(description_fr, ' »', '"') where id in (
select id from api_fieldreport where description_fr like '% »%'
);
update api_fieldreport set description_fr = replace(description_fr, 'couleur :', 'color:') where id in (
select id from api_fieldreport where description_fr like '%couleur :%'
);
update api_fieldreport set description_fr = replace(description_fr, 'couleur:', 'color:') where id in (
select id from api_fieldreport where description_fr like '%couleur:%'
);
rollback;

begin;
update api_event set summary_fr = replace(summary_fr, ' »', '"') where id in (
select id from api_event where summary_fr like '% »%'
);
update api_event set summary_fr = replace(summary_fr, 'couleur :', 'color:') where id in (
select id from api_event where summary_fr like '%couleur :%'
);
update api_event set summary_fr = replace(summary_fr, 'couleur:', 'color:') where id in (
select id from api_event where summary_fr like '%couleur:%'
);
rollback;
```

**Comment by thenav56** [comment]
Thanks, @szabozoltan69, for the fix on the database.

Looks like we missed the existing work to production. I will try to wrap this up by the end of this week.
https://github.com/IFRCGo/go-api/pull/1910

**Comment by szabozoltan69** [comment]
(I have a memory about "let's not use the new translation api version yet until there are known issues there", and were dreaming about a proxy for handling the will-not-be-implemented-to-IFRC-translation-api issues, but maybe this is a separate issue and can be handled more easily. I just mention it because it can be a background of why we did not use that PR yet.)

**Comment by thenav56** [comment]
> (I have a memory about "let's not use the new translation api version yet until there are known issues there", and were dreaming about a proxy for handling the will-not-be-implemented-to-IFRC-translation-api issues, but maybe this is a separate issue and can be handled more easily. I just mention it because it can be a background of why we did not use that logic yet.)

Hey @szabozoltan69, I think this is related to frontend static translation.

**Pull request merged**
