### PR TITLE
Updated some package versions, fix for Windows and ES

### PR DESCRIPTION
**Pull request by GregoryHorvath**
~Ran into some issues with some of the packages while setting up the project on Windows with WSL 2.~
Elasticsearch 6.0.0 that we use wanted the `urllib3` version downgrade (<1.23).

### CODE REVIEW

**Comment by batpad** [comment]
@GregoryHorvath I'd like to avoid making these changes to support alternative dev environments, especially the version downgrade. Is it possible for you to just `pip install` those specific versions in your local environment?

**Comment by GregoryHorvath** [comment]
> @GregoryHorvath I'd like to avoid making these changes to support alternative dev environments, especially the version downgrade. Is it possible for you to just `pip install` those specific versions in your local environment?

Rolled back everything except the `urllib3` change.

**Comment by batpad** [comment]
> Elasticsearch 6.0.0 that we use wanted the urllib3 version downgrade (<1.23).

@GregoryHorvath do you have a link or reference or so for this? Just curious of the context.

I see the only other place in the code `urllib3` seems to be used is the `scrape_pdf` management command - if @thenav56 is confident this won't affect that, I'm fine to merge - but still curious why a version downgrade is needed exactly.

**Comment by thenav56** [comment]
> > Elasticsearch 6.0.0 that we use wanted the urllib3 version downgrade (<1.23).
> 
> @GregoryHorvath do you have a link or reference or so for this? Just curious of the context.
> 
> I see the only other place in the code `urllib3` seems to be used is the `scrape_pdf` management command - if @thenav56 is confident this won't affect that, I'm fine to merge - but still curious why a version downgrade is needed exactly.

`scrape_pdf` is addition by @GregoryHorvath . He will have more idea what to check there.

But viewing the changelog between [1.24](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#124-2018-10-16) and [1.22](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#122-2017-07-20) I don't see any major changes affecting the use cases. But @GregoryHorvath should have more idea.

```
1.24 (2018-10-16)

    Allow key_server_hostname to be specified when initializing a PoolManager to allow custom SNI to be overridden. (Pull #1449)
    Test against Python 3.7 on AppVeyor. (Pull #1453)
    Early-out ipv6 checks when running on App Engine. (Pull #1450)
    Change ambiguous description of backoff_factor (Pull #1436)
    Add ability to handle multiple Content-Encodings (Issue #1441 and Pull #1442)
    Skip DNS names that can't be idna-decoded when using pyOpenSSL (Issue #1405).
    Add a server_hostname parameter to HTTPSConnection which allows for overriding the SNI hostname sent in the handshake. (Pull #1397)
    Drop support for EOL Python 2.6 (Pull #1429 and Pull #1430)
    Fixed bug where responses with header Content-Type: message/* erroneously raised HeaderParsingError, resulting in a warning being logged. (Pull #1439)
    Move urllib3 to src/urllib3 (Pull #1409)

1.23 (2018-06-04)

    Allow providing a list of headers to strip from requests when redirecting to a different host. Defaults to the Authorization header. Different headers can be set via Retry.remove_headers_on_redirect. (Issue #1316)
    Fix util.selectors._fileobj_to_fd to accept long (Issue #1247).
    Dropped Python 3.3 support. (Pull #1242)
    Put the connection back in the pool when calling stream() or read_chunked() on a chunked HEAD response. (Issue #1234)
    Fixed pyOpenSSL-specific ssl client authentication issue when clients attempted to auth via certificate + chain (Issue #1060)
    Add the port to the connectionpool connect print (Pull #1251)
    Don't use the uuid module to create multipart data boundaries. (Pull #1380)
    read_chunked() on a closed response returns no chunks. (Issue #1088)
    Add Python 2.6 support to contrib.securetransport (Pull #1359)
    Added support for auth info in url for SOCKS proxy (Pull #1363)

1.22 (2017-07-20)

    Fixed missing brackets in HTTP CONNECT when connecting to IPv6 address via IPv6 proxy. (Issue #1222)
    Made the connection pool retry on SSLError. The original SSLError is available on MaxRetryError.reason. (Issue #1112)
    Drain and release connection before recursing on retry/redirect. Fixes deadlocks with a blocking connectionpool. (Issue #1167)
    Fixed compatibility for cookiejar. (Issue #1229)
    pyopenssl: Use vendored version of six. (Issue #1231)
```

**Comment by GregoryHorvath** [comment]
I only found this: https://github.com/elastic/elasticsearch-py/issues/807
`Collecting urllib3<1.24,>=1.21.1 (from requests)`

In our case we still have ES 6.0.0 everywhere and it said `<1.23` at one part when I was installing the packages from `requirements.txt`. It was probably just a warning, but I didn't really catch it sadly.

**Comment by batpad** [comment]
If nothing is broken with the current packages, can we skip fixing? :)

We can do a separate round of updating packages, but let's do that in an organized way. I'd vote to just close this for now.

**Pull request closed without merging**
