### PR TITLE
Change all informal to flash

### PR DESCRIPTION
**Pull request by Rup-Narayan-Rajbanshi**
Addresses Informal Update 

## Changes

- Add validations for files <= 3
- Add validations for unique country
- Delete informal_update/ and added flash_update/

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by szabozoltan69** [comment]
What about the already done migrations? Shall we delete it manually from django_migrations data table? Or shall we create new migration files?

**Comment by szabozoltan69** [comment]
@Rup-Narayan-Rajbanshi what do you think about the question above?

**Comment by frozenhelium** [comment]
@szabozoltan69 Yes, I think we should remove the table related to informal update in the db.

CC: @Rup-Narayan-Rajbanshi

**Comment by szabozoltan69** [comment]
Deployed to Staging environment

**Pull request merged**
