### PR TITLE
Feature/search page feedback

### PR DESCRIPTION
**Pull request by k9845**
Addresses 
 - https://github.com/IFRCGo/go-frontend/issues/2595
 - https://github.com/IFRCGo/go-api/issues/1700
## Changes
- New field in indexing fields

# NOTE:
@szabozoltan69 Please run `docker-compose exec serve bash python manage.py update_index`

## Checklist 
Things that should succeed before merging.

- [x] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by k9845** [comment]
@szabozoltan69  Please merge this PR and deploy to staging and run `docker-compose exec serve bash python manage.py update_index`

**Comment by szabozoltan69** [comment]
Great work, thanks for solving also https://github.com/IFRCGo/go-api/issues/1700 via this PR!

**Comment by szabozoltan69** [comment]
@k9845 Deployed to Staging.
update_index has been run:
```
Indexing 5 regions
Indexing 285 countries
Indexing 3563 districts
Indexing 4427 emergencies
...
```

**Comment by szabozoltan69** [comment]
There was an issue in project indexing (which can be my fault, due to sector changes).
Is it possible to set this job to update only one specific entity (for testing)?

The issue was:
The model ''<Project: ...>'' does not have a model_attr 'get_primary_sector_display'.

**Comment by szabozoltan69** [comment]
Now there was a flawless run on Staging:
```
~/go-api# ./manage.py update_index 
Indexing 5 regions
Indexing 285 countries
Indexing 3563 districts
Indexing 4427 emergencies
Indexing 3693 appeals
Indexing 10101 field reports
Indexing 350 Surge Alerts
Indexing 25 Emergency Response Units
Indexing 1720 Projects
Indexing 138 drefs
Indexing 60 Dref Operational Updates
Indexing 28 Flash updates
```

**Pull request merged**
