### PR TITLE
Hot fix/emergency 3w model

### PR DESCRIPTION
**Pull request by k9845**
## Changes
- Update database field in emergency 3W..

## Checklist 
Things that should succeed before merging.

- [x] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by frozenhelium** [comment]
@szabozoltan69 Please, merge and deploy this hotfix to both the staging and the prod

CC: @tovari

**Comment by szabozoltan69** [comment]
Ok, I can do it, but normally a hotfix should be branched from master.
Because this way some half-ready stuffs (e.g. my ones) will go to master.

**Comment by frozenhelium** [comment]
@szabozoltan69 Noted! We'll do that from next time. Thanks!

**Comment by szabozoltan69** [comment]
Deployed to staging – now I merge to master.

**Comment by szabozoltan69** [comment]
Deployed to prod.

**Pull request merged**
