### PR TITLE
alternate approach to admin redirect

### PR DESCRIPTION
**Pull request by batpad**
@szabozoltan69 this was my idea to handle the `admin` redirect - can you let me know if this works? I'm slightly confused with the handling of the `language` parameter - but I think this should be a cleaner separation of the admin URLs than what we have right now.

### CODE REVIEW

**Comment by batpad** [comment]
cc @thenav56

**Comment by szabozoltan69** [comment]
This solution is great. Works perfectly for me.
Also the original https://github.com/IFRCGo/go-api/issues/1594 issue is solved:
```
curl -isL 'http://localhost:8000/api/v2/region/9/'
HTTP/1.1 404 Not Found
Date: Mon, 12 Dec 2022 15:45:22 GMT
Server: WSGIServer/0.2 CPython/3.8.12
Content-Type: application/json
Vary: Accept, Accept-Language, Origin, Cookie
Allow: GET, HEAD, OPTIONS
X-Frame-Options: DENY
Content-Length: 23
Content-Language: en
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin

{"detail":"Not found."}
```
This is a great solution because this way the [process_response of site-packages/django/middleware/locale.py](https://github.com/django/django/blob/main/django/middleware/locale.py#L72)
works fine, path_valid remains false in case of erroneuos ID request.

**Comment by szabozoltan69** [comment]
Before merging we should consider that there are some points on frontend where we turn the user to the admin page, e.g. Emergency edit. These should be also aligned with this change (inserting /admin into the URL).

**Comment by thenav56** [comment]
Totally agree with these changes. This will also solve the issue with the language redirect fixed by https://github.com/IFRCGo/go-api/pull/1609.

I am just concerned about the usage of the admin URLs if it is shared with others.

**Comment by batpad** [comment]
@szabozoltan69 sorry for the delay here! Maybe let's not push into this production release, but immediately after we can merge this to develop, make sure we test well on staging and then get this into the next release?

**Comment by szabozoltan69** [comment]
Good approach!
And it has some frontend task also ("Edit Event" link to be changed).

**Pull request closed without merging**
