### PR TITLE
make subprocess wait to finish the commands

### PR DESCRIPTION
**Pull request by geohacker**
This addresses the mapbox update command from creating invalid geojsons. I still run into a weird SIGKILL 9 which I can't figure out why. 

@batpad @szabozoltan69 could you test this locally?

### CODE REVIEW

**Comment by geohacker** [comment]
This is not ready for merging yet

**Comment by szabozoltan69** [comment]
For me it run fine locally.
I did not see any SIGKILL error. (Or maybe it is not visible?)
At the end there was no background-running process.

```
root@c683700c0d68:~/go-api# ./manage.py update-mapbox-tilesets
Exporting countries...
Countries written to /tmp/countries.geojson
Exporting districts...
Districts written to /tmp/districts.geojson
Exporting country centroids...
Exporting district centroids...
Update Mapbox tileset source for countries...
upload progress  [==========================================================================================================================================================================================]  100%
{"id": "mapbox://tileset-source/go-ifrc/go-countries-src", "files": 1, "source_size": 337086395, "file_size": 337086395}
Update Mapbox tileset for countries...
{"message": "Processing go-ifrc.go-countries", "jobId": "ckoxxi3zs000k07mla8j7h7ba"}

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/go-ifrc.go-countries or run tilesets job go-ifrc.go-countries ckoxxi3zs000k07mla8j7h7ba to view the status of your tileset.
Update Mapbox tileset source for districts...
upload progress  [==========================================================================================================================================================================================]  100%
{"id": "mapbox://tileset-source/go-ifrc/go-districts-src-1", "files": 1, "source_size": 298704506, "file_size": 298704506}
Update Mapbox tileset for districts...
{"message": "Processing go-ifrc.go-districts-1", "jobId": "ckoxxk11n000008jo5234etsj"}

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/go-ifrc.go-districts-1 or run tilesets job go-ifrc.go-districts-1 ckoxxk11n000008jo5234etsj to view the status of your tileset.
Update Mapbox tileset source for country centroids...

{"id": "mapbox://tileset-source/go-ifrc/go-country-centroids", "files": 1, "source_size": 79215, "file_size": 79215}
Update Mapbox tileset for country centroids...
{"message": "Processing go-ifrc.go-country-centroids", "jobId": "ckoxxk6a8000908mrgsx6cgq0"}

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/go-ifrc.go-country-centroids or run tilesets job go-ifrc.go-country-centroids ckoxxk6a8000908mrgsx6cgq0 to view the status of your tileset.
Update Mapbox tileset source for district centroids...

{"id": "mapbox://tileset-source/go-ifrc/go-district-centroids", "files": 1, "source_size": 614492, "file_size": 614492}
Update Mapbox tileset for district centroids...
{"message": "Processing go-ifrc.go-district-centroids", "jobId": "ckoxxkhfu000n07mlcmvca194"}

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/go-ifrc.go-district-centroids or run tilesets job go-ifrc.go-district-centroids ckoxxkhfu000n07mlcmvca194 to view the status of your tileset.
```
Listing the temporary files:
```
root@c683700c0d68:/tmp# ls -lrt
total 748468
drwxr-xr-x 2 root root      4096 May 21 06:00 opencensus-python-fa128365-fb09-4568-b944-b05e38b6b94c
-rw-r--r-- 1 root root 408842963 May 21 06:12 countries.geojson
-rw-r--r-- 1 root root 356780707 May 21 06:13 districts.geojson
-rw-r--r-- 1 root root     80543 May 21 06:13 country-centroids.geojson
-rw-r--r-- 1 root root    707832 May 21 06:13 district-centroids.geojson
```

**Comment by szabozoltan69** [comment]
It is not quite clear where is the "outcome" of this manage.py update-mapbox-tilesets run. Does some jobs run at studio.mapbox.com and we are glad to see it? Or will the result somehow return back to GO side?

**Comment by geohacker** [comment]
@szabozoltan69 this looks great and is what I'd expect. It has kicked off tileset jobs on Mapbox. I think we can merge this.

**Review by batpad — APPROVED** [review]

**Comment by batpad** [comment]
@geohacker looks good -  will need to resolve some conflict though.

**Comment by szabozoltan69** [comment]
Could you @geohacker please solve this conflict? api/management/commands/update-mapbox-tilesets.py
Or maybe just override the old one with your file.

**Comment by geohacker** [comment]
@batpad @szabozoltan69 done!

**Pull request merged**
