### PR TITLE
Fix/set new user as non guest

### PR DESCRIPTION
**Pull request by Rup-Narayan-Rajbanshi**
Addresses
  - https://github.com/IFRCGo/go-web-app/issues/1371

## Changes
  - Set new user to non-guest user.

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Review by thenav56 — APPROVED** [review]

**Comment by szabozoltan69** [comment]
Should we merge this? (It's still in Draft.)

**Comment by thenav56** [comment]
@szabozoltan69 Let's merge and deploy to staging for a quick QA.

**Review by szabozoltan69 — APPROVED** [review]

**Comment by szabozoltan69** [comment]
Deployment to Staging is done.
```
Running migrations:
  Applying api.0214_alter_profile_limit_access_to_guest... OK
```

**Comment by szabozoltan69** [comment]
Can I ask that QC is ok with this?
(Because if ok, then (with other fixes) a simple develop->master could be one.)

**Comment by shraeyaa** [comment]
Hi Zoltan, I have completed the testing. Can proceed. @szabozoltan69 
cc @udaynwa

**Comment by szabozoltan69** [comment]
Deployed to Prod – thanks for the testing, Shreya.

**Pull request merged**
