### PR TITLE
Fix null enum type

### PR DESCRIPTION
**Pull request by k9845**
## Changes
- Fix null for enums in schema generation

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by frozenhelium** [comment]
@thenav56 Let's review and merge this

**Comment by szabozoltan69** [comment]
There is a dispute on this e.g. [here](https://github.com/tfranzel/drf-spectacular/issues/235).
We could consider also this: https://github.com/tfranzel/drf-spectacular/issues/235#issuecomment-847238540

**Comment by k9845** [comment]
Already resolved by PR https://github.com/IFRCGo/go-api/pull/2063

**Comment by k9845** [comment]
Resolved by PR https://github.com/IFRCGo/go-api/pull/2063

**Pull request closed without merging**
