### PR TITLE
Replace enum Choices to models Choices

### PR DESCRIPTION
**Pull request by Rup-Narayan-Rajbanshi**
Addresses IFRC Go

## Changes
- Replace enum Choices to models Choices

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Review by thenav56 — APPROVED** [review]
LGTM
Can you make sure no new migrations will be created using./manage.py makemigrations?

**Comment by szabozoltan69** [comment]
From who do you ask that question, @thenav56 ? :-)

**Comment by Rup-Narayan-Rajbanshi** [comment]
> LGTM Can you make sure no new migrations will be created using./manage.py makemigrations?

yes I tried to make makemigrations , but no new  migrations were created.

**Comment by Rup-Narayan-Rajbanshi** [comment]
> From who do you ask that question, @thenav56 ? :-)
@

**Comment by thenav56** [comment]
> From who do you ask that question, @thenav56 ? :-)

It was for @Rup-Narayan-Rajbanshi .

**Comment by szabozoltan69** [comment]
```
No changes detected
Running migrations:
  No migrations to apply.
```

**Comment by szabozoltan69** [comment]
Deployed to staging

**Pull request merged**
