### PR TITLE
Feature/settings refactor

### PR DESCRIPTION
**Pull request by thenav56**
Addresses Refactor settings.py 

## Changes

* Centralize storage configuration. No more `storage=` in FileFileld or ImageField.
* Add django-environ.

## Attention
- Need to update .env.
  - DEBUG_EMAIL supports true/false now instead of 0/1.
  - Add GO_ENVIRONMENT.  Value can be `staging`, `production`, `development`.
    - `development` is default.
    - `production` value will hide banner in admin panel.
    

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by thenav56** [comment]
@batpad @vdeak @szabozoltan69 Do we need to use two separate domains for the server? Instead, just pass `goadmin.ifrc.org` through env instead of using this logic? (Not pass/use `prddsgocdnapi.azureedge.net` in go-api server configuration)
https://github.com/IFRCGo/go-api/blob/39785fde886401c48a33afd3a304466457f15150/main/settings.py#L68-L69

**Review by szabozoltan69 — CHANGES_REQUESTED** [review]
Brilliant changes. It was high time to get these settings in order. MANY THANKS!

One more task: please have a look at https://github.com/IFRCGo/go-api/blob/develop/main/runserver.sh#L14 – can we remove this ugly sed replace? Or if not, is is usable in the recent situation?

**Comment by szabozoltan69** [comment]
@thenav56  No problem with the "only goadmin..." principle; we should change the client side also via https://github.com/IFRCGo/go-frontend/blob/develop/src/root/config.js

**Comment by thenav56** [comment]
@szabozoltan69 
Yes, we can now pass additional allowed hosts like this.

```env
API_FQDN=goadmin.ifrc.org
DJANGO_ADDITIONAL_ALLOWED_HOSTS=api.go.ifrc.org,prddsgocdnapi.azureedge.net
```

**Comment by thenav56** [comment]
Another question, @IFRCGo/backend-dev 
Is there a reason behind defining these environment variables in circle-ci?
https://app.circleci.com/settings/project/github/IFRCGo/go-api/environment-variables

To allow environment variables in the docker-compose.yml to be mutable using the .env file I need to remove those values as they are overwriting the default configuration in circle-ci.

**Comment by szabozoltan69** [comment]
I think you can remove the circle-ci variables without problem, @thenav56

**Review by szabozoltan69 — APPROVED** [review]

**Comment by thenav56** [comment]
@szabozoltan69 If everything is good, could you merge and deploy to staging? This will fix the file issue related to DREF and flash-update.

**Comment by thenav56** [comment]
Make sure to update .env as well.

**Comment by szabozoltan69** [comment]
Deployed to staging

**Comment by batpad** [comment]
This looks really good to me, thanks @thenav56

**Comment by szabozoltan69** [comment]
Could I remove this row?
https://github.com/IFRCGo/go-api/blob/develop/main/runserver.sh#L14

**Comment by thenav56** [comment]
Yes, please.

**Pull request merged**
