### PR TITLE
Remove image fields

### PR DESCRIPTION
**Pull request by k9845**
## Changes
 - Remove image fields from dref-final-report
 
## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by k9845** [comment]
@szabozoltan69 Let's merge this to staging and production.

**Comment by szabozoltan69** [comment]
Staging deployment is done, soon the Prod will also...

**Comment by szabozoltan69** [comment]
For master I use this: https://github.com/IFRCGo/go-api/pull/1722

**Comment by szabozoltan69** [comment]
Hotfix deployed to Prod

**Pull request merged**
