### PR TITLE
Feature/auto translation

### PR DESCRIPTION
**Pull request by thenav56**
Addresses Auto Dynamic translation 

### Configuration
We need to set these variables to use the IFRC translation service
```env
AUTO_TRANSLATION_TRANSLATOR=lang.translation.IfrcTranslator
IFRC_TRANSLATION_URL=https://XXXXXXXXXXXXX-XXXXXXX.ifrc.org/Translation/api/translate
IFRC_TRANSLATION_API_KEY=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

### CODE REVIEW

**Review by szabozoltan69 — APPROVED** [review]

**Comment by szabozoltan69** [comment]
@thenav56 I tested locally this branch, seems to be fine.
The migrations were running quite a minute time long. :-)
Could you suggest me a place on the Admin website where the effect (or some extra fields) of the auto-translation should be seen? (No worries, if not – just I am curious.)

**Comment by thenav56** [comment]
> @thenav56 I tested locally this branch, seems to be fine. The migrations were running quite a minute time long. :-) Could you suggest me a place on the Admin website where the effect (or some extra fields) of the auto-translation should be seen? (No worries, if not – just I am curious.)

Hey @szabozoltan69 
You should be able to see a `skip auto translation` field on the Appeal page.

You can also look at the migrations files, any model with changes should have the skip field in there.

**Comment by szabozoltan69** [comment]
Ok, I see that:
kép

**Comment by szabozoltan69** [comment]
@thenav56 – deployed to Staging (via develop branch)

**Pull request merged**
