### PR TITLE
Feature/dref permission

### PR DESCRIPTION
**Pull request by k9845**
Addresses 
- https://github.com/IFRCGo/go-frontend/issues/2618

## Changes
- Setup permission in dref
- Flake8 fixes

## Checklist 
Things that should succeed before merging.

- [x] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

### CODE REVIEW

**Comment by k9845** [comment]
@szabozoltan69 Could you merge this to staging? Seems like frontend changes are already merged.

**Comment by szabozoltan69** [comment]
Yes, I merge it to develop and deploy it to staging, thanks for the idea!

**Comment by szabozoltan69** [comment]
Just one question: is double-quotes (") better than apostrophe (')?
Or why did you change all of them? :-) @k9845

**Comment by k9845** [comment]
@szabozoltan69 Thanks. I ran flake8 it prefers `"` over `'`. Maybe we should now add a flake8 check.

**Comment by szabozoltan69** [comment]
Deployed to staging

**Comment by szabozoltan69** [comment]
Deployed to Prod also.

**Pull request merged**
