### PR TITLE
Update Project's status automatically

### PR DESCRIPTION
**Pull request by thenav56**
Addresses 3W: Project status does not auto-update from "planned" to "ongoing" once start date is reached https://github.com/IFRCGo/go-frontend/issues/1181

## Changes
* Added cronjob which updates project's status using start/end date. cc: @frozenhelium 
* Updated Personnel test using snapshot for **csv** API.
* Using **pytest** as test runner.

### CODE REVIEW

**Comment by thenav56** [comment]
@szabozoltan69 @batpad I am using pytest here. It is more readable and has good plugins support if needed.

Differences in the test output:
[Pytest] https://app.circleci.com/pipelines/github/IFRCGo/go-api/1224/workflows/a4120e84-63ad-42ac-a96b-9a149703e94f/jobs/3101/parallel-runs/0/steps/0-103
[Django test] https://app.circleci.com/pipelines/github/IFRCGo/go-api/1223/workflows/becaa823-e22a-40f2-9a19-051c19b6554f/jobs/3100/parallel-runs/0/steps/0-103

**Comment by szabozoltan69** [comment]
@thenav56 Great, that circleCI can use pytest!
Is it possible to keep the existing "legacy" tests cases and also use this new one also?

**Review by szabozoltan69 — APPROVED** [review]

**Comment by thenav56** [comment]
> @thenav56 Great, that circleCI can use pytest!
> Is it possible to keep the existing "legacy" tests cases and also use this new one also?

@szabozoltan69 pytest runs similar to Django's test framework but provides additional configuration and good visualization. So all current tests will be executed as usual. You can see that on the link I shared above.
image
image


`python3 manage.py test` will also always work. But I have modified `docker-compose.yml test` to pytest so in circle-ci it will use pytest.

**Comment by szabozoltan69** [comment]
Ok, it should be merged soon.
(There is an ongoing knowledge transfer to an Atos boy, so it will be an example deployment in an hour.)

**Comment by vdeak** [comment]
Deployed to Staging

**Pull request merged**
