### PR TITLE
Sentry Cron Job Monitoring

### PR DESCRIPTION
**Pull request by susilnem**
Addresses 
- https://github.com/IFRCGo/go-api/issues/2010

## Changes
 - Add Command for creating slug for respective Cron jobs
 - Add monitoring slug to the cron jobs: https://docs.sentry.io/product/crons/
 
 
 ### NOTE: We need to initialize the sentry cron configuration using this command
```bash
./manage.py cron_job_monitor
```
> NOTE: Any change in SentryMonitor requires above command for sync

> NOTE: This will push updates to https://sentry.northeurope.cloudapp.azure.com/organizations/ifrc-go/crons/?project=2

### CODE REVIEW

**Review by thenav56 — APPROVED** [review]

**Comment by thenav56** [comment]
@szabozoltan69 When you have time, could you review and merge this PR.

**Comment by thenav56** [comment]
@szabozoltan69 When you deploy these changes, please run the commands mentioned in the descriptions above ☝🏽

**Comment by szabozoltan69** [comment]
Deployment to Staging started.

**Comment by szabozoltan69** [comment]
Hi @thenav56 , unfortunately the above manage command did not run fine in the vm. The "deploy" subdir can not be seen for the deployed system.
(Gave a FileNotFoundError: [Errno 2] No such file or directory: '/home/ifrc/go-api/deploy/helm/ifrcgo-helm/values.yaml' )

**Comment by thenav56** [comment]
Thanks, @szabozoltan69 

I forget deploy wasn't included in the go-api build. For now, we can comment out this line and re-run https://github.com/IFRCGo/go-api/blob/2da387f182e6bef60e014460c03aecd86ef282fc/api/management/commands/cron_job_monitor.py#L26

We will push another fix PR for future. [Will show a warning message instead of error]

**Comment by szabozoltan69** [comment]
This way the run was fine:
```
:~/go-api# ./manage.py cron_job_monitor
Successfully created cron job for index_and_notify
Successfully created cron job for sync_molnix
Successfully created cron job for ingest_appeals
Successfully created cron job for sync_appealdocs
Successfully created cron job for revoke_staff_status
Successfully created cron job for update_project_status
Successfully created cron job for user_registration_reminder
Successfully created cron job for ingest_country_plan_file
Successfully created cron job for update_surge_alert_status
```

**Pull request merged**
